### ISSUE TITLE
Supports order list and bullet list

### ISSUE THREAD

**Issue by TinyCricetus** [textbus/xnote#1]
# Implements

## Bullet list
- item
- item
- item

### Normal list
1. item
2. item
3. item

### Composition list
***A list that supports serial number inheritance.***

1. item
2. item
[todolist]
Here are some other components.
[picture]
3. item

**Comment by textbus** [comment]
Thank you for your suggestion. The list function has been implemented. Welcome to visit https://textbus.io/playground/
